#!/usr/bin/env bash
echo \
"Um texto random, tudo bem com voce?" 
#PULANDO LINHA
echo -e "Vinicius Soares is \nAprendendo."
#modo tab
echo -e "Eu gosto de \tanimes!"
#vertical modo
echo -e "Anime e coisa de \vCrianca."
